# Generated by Django 2.2 on 2023-02-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=50)),
                ('hobby_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_item_name', models.CharField(max_length=50)),
                ('portfolio_item_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
