# Generated by Django 2.2 on 2023-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/005/068/699/original/a-simple-gear-logo-or-icon-design-vector.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio_item',
            name='hobby_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/005/068/699/original/a-simple-gear-logo-or-icon-design-vector.jpg', max_length=500),
        ),
    ]
