# Generated by Django 2.2 on 2023-02-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_auto_20230222_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio_item',
            old_name='hobby_image',
            new_name='portfolio_image',
        ),
    ]
